site_name: My Docs
site_url: https://github.com/nmakke/MkDocsTest/

repo_url: https://github.com/nmakke/MkDocsTest/

theme:
  name: material
nav:
    - Home: index.md
    
plugins:
  - search
  - table-reader
  
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
markdown_extensions:
  - mdx_math

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.expand
    - toc.follow
    - navigation.top
    # - toc.integrate
    - search.share
    - search.suggest
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
