site_name: My Docs
site_url: https://github.com/nmakke/MkDocsTest/
theme:
  name: material
nav:
    - Home: index.md
    - Article: article.md
    - Recent: recent.md
    - About: about.md
    - Contribute: contribute.md
