site_name: My Docs
site_url: https://github.com/nmakke/MkDocsTest/

repo_url: https://github.com/nmakke/MkDocsTest/

theme:
  name: material
nav:
    - Home: index.md
    - About: about.md
    - Methods: methods.md
    - Datasets: datasets.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.expand
    - toc.follow
    - navigation.top
    # - toc.integrate
    - search.share
    - search.suggest
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
