site_name: My Docs
site_url: https://github.com/nmakke/MkDocsTest/

repo_url: https://github.com/nmakke/MkDocsTest/

theme:
  name: material
nav:
    - Home: index.md
    - About: about.md
    - Methods: methods.md
    - Datasets: datasets.md
